### ISSUE TITLE
Camera and gallery not working

### ISSUE THREAD

**Issue by Ulugbe7** [GhayasAhmad/auto-background-remover#1]
Hello everyone. I try to remove image background. When I pick image from drawable  this library work normally, but pick from gallery or camera it is not working. If anyone solve this issue can you share with me?

**Comment by krunaljha** [comment]
I solve this issue , you just have to change your immutable bitmap to a mutable bitmap, and for more details you can refer the https://developers.google.com/ml-kit/vision/selfie-segmentation/android.
