### ISSUE TITLE
failed to resolve 

### ISSUE THREAD

**Issue by ngarangan** [GhayasAhmad/auto-background-remover#3]
failed to resolve: com.github.GhayasAhmad:auto-background-remover:1.0.3

**Comment by GhayasAhmad** [comment]
`maven { url 'https://jitpack.io' }`

add this in your gradle all project repositories

**Comment by GhayasAhmad** [comment]
![image](https://user-images.githubusercontent.com/65961727/197358944-3e92dc4c-d8b4-4a3b-86f9-6272bd248d0b.png)

properly add these it will work.
