### ISSUE TITLE
Image Border is not smooth after background Removed.

### ISSUE THREAD

**Issue by Shahidzbi4213** [GhayasAhmad/auto-background-remover#4]
**That's My Code**
![image](https://user-images.githubusercontent.com/45350491/204790413-9cc33513-5dab-4772-8fe9-2ecac719da48.png)

**Check the Image**
![image](https://user-images.githubusercontent.com/45350491/204789633-c4171c4c-ebdb-4046-ba68-4639c12e704f.png)

**Comment by GhayasAhmad** [comment]
This is not an issue my brother.

**Comment by GhayasAhmad** [comment]
In further updated ill add this feature to convert sharp edges to smooth.

**Comment by Shahidzbi4213** [comment]
Bro I m working on app which contain images of which background need to be removed but what library did instead of background all the image has been remove. check that video i am attaching you will get the idea.

https://user-images.githubusercontent.com/45350491/209426610-4e21c904-c1c2-4466-969a-e8092f0fbe3c.mp4

**Comment by Shahidzbi4213** [comment]
> In further updated ill add this feature to convert sharp edges to smooth.

that would be great also check the following the comment down

**Comment by GhayasAhmad** [comment]
Yeah, I know when you give an image in which the subject is not clear this library erases the complete image.

**Comment by Shahidzbi4213** [comment]
ohh okay got  it i will have to go for slazzer thn my badluck :P
